### ISSUE TITLE
My content is not being displayed

### ISSUE THREAD

**Issue by hprez21** [WeAreDotnet/dotnet-creator-cards#164]
**Describe the bug**
Hi, my [card ](https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/hector-perez.json)is updated with feeds from my blog and YouTube. Yesterday I posted a video on my YouTube channel, which appears properly in the [feed](https://www.youtube.com/feeds/videos.xml?channel_id=UClmm_8Uj7R30F9JHe-3nj5w), however, it did not appear on the content wall.

**To Reproduce**
1.- Go to https://www.wearedotnet.io/
2.- My content doesn't appear

**Comment by matthiasjost** [comment]
@DeeJayTC I see Hector is not yet a creator when I go to his profile: https://www.wearedotnet.io/hprez21

Is there a particular reason for it, or can we just make him a creator?

**Comment by DeeJayTC** [comment]
Need to check in the database, did you link his card and make him a creator?

**Comment by DeeJayTC** [comment]
Yea @matthiasjost he was never linked, can you do that (but manually please)

**Comment by matthiasjost** [comment]
I will check that.

**Comment by matthiasjost** [comment]
I have linked your card with your account. I have yet to see any changes to your profile.
That could be due to the fact that there must be some stuff running in the background.

However, in case you want to look into it @DeeJayTC , here is his card:
https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/hector-perez.json

**Comment by DeeJayTC** [comment]
Works properly now :)

**Comment by hprez21** [comment]
Thank you very much @DeeJayTC  @matthiasjost !
